server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: /tmp/positions.yaml

clients:
  - url: http://localhost:3100/loki/api/v1/push

scrape_configs:
  - job_name: order-service
    static_configs:
      - targets: [localhost]
        labels:
          job: order-service
          __path__: /Users/sowri/Documents/order-service/logs/order-service.log
  - job_name: notification-service
    static_configs:
      - targets: [localhost]
        labels:
          job: notification-service
          __path__: /Users/sowri/Documents/notification-service/logs/notification-service.log
